name: gng_getaways
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  routemaster: ^1.0.1
  flutter_native_splash: ^2.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
#flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
  web: true
  web_image_mode: center
